module.exports = {
    css: [

    ],
    onsenUI: {
        VOnsToolbar: true,
        VOnsBottomToolbar: true,
        VOnsToolbarButton: true,
        VOnsAlertDialogButton: true,
        VOnsButton: true,
        VOnsIcon: true,
        VOnsCard: true,
        VOnsList: true,
        VOnsListItem: true,
        VOnsListTitle: true,
        VOnsListHeader: true,
        VOnsRipple: true,
        VOnsRow: true,
        VOnsCol: true,
        VOnsProgressBar: true,
        VOnsProgressCircular: true,
        VOnsCarouselItem: true,
        VOnsSplitterMask: true,
        VOnsSplitterContent: true,
        VOnsSplitter: true,
        VOnsSwitch: true,
        VOnsCheckbox: true,
        VOnsInput: true,
        VOnsSearchInput: true,
        VOnsRange: true,
        VOnsRadio: true,
        VOnsFab: true,
        VOnsSpeedDialItem: true,
        VOnsDialog: true,
        VOnsActionSheet: true,
        VOnsActionSheetButton: true,
        VOnsModal: true,
        VOnsToast: true,
        VOnsPopover: true,
        VOnsAlertDialog: true,
        VOnsSpeedDial: true,
        VOnsCarousel: true,
        VOnsTab: true,
        VOnsTabbar: true,
        VOnsBackButton: true,
        VOnsNavigator: '_CORE/components/onsenui/v-ons-navigator.js',
        VOnsSplitterSide: true,
        VOnsLazyRepeat: true,
        VOnsSelect: true,
        VOnsSegment: true,
        VOnsPullHook: true,
        VOnsPage: true,

    },
    directives: {
        InputNext: true,
        ImageCache: true,
        InputMask: true,
        Analytics: true,
        GoogleMaps: true,
        StatusBarFill: true,
        HoldCallback: true,
        Browser: true,
        ShowPassword: true,
        Guide: false,
        Autofocus: false,
        OnceRendered: false,
        OnsModalOnScroll: false,
        Clipboard: true,
    },
    filters: {
        searchText: true,
        toCoins: true,
        toMoney: true,
        numberFormat: true,
        maskCard: true,
        currencyMX: true,
        currencyToSymbol: true,
        currency: true,
        capitalize: false,
        date: true,
        percentage: false,
    },
    store: {
        App: true,
        User: true,
        PayCards: true,
        Payments: true,
        Ewallet: true,
        P2P: true,
        Catalog: '_CORE/modules/Catalog/Base/store/modules/Catalog',
        PhoneMasks: true,
        Exchange: false,
        BankAccounts: '_CORE/modules/BankAccounts/store/modules/BankAccounts',
        PaymentTemplates: '_CORE/modules/PaymentTemplates/store/modules/PaymentTemplates',
        Core: true,
        History: true,
        Banners: '_CORE/modules/Banners/store/modules/Banners',
        AppState: true,
        PaymentMethods: false,
        Faq: '_CORE/modules/Faq/store/modules/Faq',
        Maps: false,
        Policy: false,
        Promotions: false,
        Bank: {
            Deposits: false,
            Credits: false,
        },
        Payment: {
            Cards: {
                Block: false,
                Limits: false,
            },
            P2P: {
                Invoice: false,
            },
        },
        MobiGift: '_CORE/modules/Gifts/store/modules/MobiGift',
    },
    components: {
        ProgressCircular: '_progress_circular',
        AlertConfirm: '_alert_confirm',
        VueInspector: '_vue_inspector',
        layout: true,
        LayoutDefault: '_CORE/layouts/default',
    },
    // Vue.prototype.$Name = Name;
    plugins: {
        VeeValidate: true,
        VueTextareaAutosize: 'vue-textarea-autosize'
    },
    mixins: {
        MixinCommon: true
    },
    mwalletClient: {
        Core: true,
        Registration: true,
        User: true,
        Masterpass: true,
        PaymentMethods: true,
        PaymentCards: true,
        Payments: true,
        Ewallet: true,
        P2P: true,
        // Catalog: {
        //     EasyPay: true,
        // },
        Catalog: '_CORE/modules/Catalog/Base/libs/Catalog',
        Exchange: false,
        BankAccounts: '_CORE/modules/BankAccounts/libs/BankAccounts',
        Faq: '_CORE/modules/Faq/libs/Faq',
        Policy: false,
        Promotions: false,
        Maps: false,
        Bank: {
            Deposits: false,
            Credits: false,
        },
        Payment: {
            Cards: {
                Block: false,
                Limits: false,
            },
            P2P: {
                Invoice: false,
            },
        },
    },
};
